# Generated by Django 5.2.1 on 2025-05-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='name', max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='famili', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='properties_owned',
            field=models.ManyToManyField(blank=True, related_name='owner_properties', to='estateAgency.property'),
        ),
    ]
