# Generated by Django 5.2.1 on 2025-05-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0004_aboutcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name': 'About Company', 'verbose_name_plural': 'About Company'},
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='description',
            field=models.TextField(verbose_name='description '),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='details',
            field=models.TextField(verbose_name='Details'),
        ),
    ]
