# Generated by Django 5.2.1 on 2025-05-29 11:04

import estateAgency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0005_alter_aboutcompany_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='Должно быть не менее 18 лет', validators=[estateAgency.models.validate_age], verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='Должно быть не менее 18 лет', validators=[estateAgency.models.validate_age], verbose_name='Возраст'),
        ),
    ]
