# Generated by Django 5.2.1 on 2025-05-29 13:45

import estateAgency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0006_client_age_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(default=estateAgency.models.get_default_birth_date, help_text='Должно быть не менее 18 лет', validators=[estateAgency.models.validate_birth_date], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=estateAgency.models.get_default_birth_date, help_text='Должно быть не менее 18 лет', validators=[estateAgency.models.validate_birth_date], verbose_name='Дата рождения'),
        ),
    ]
