# Generated by Django 5.2.1 on 2025-05-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0007_remove_client_age_remove_employee_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(max_length=100, verbose_name='Должность / роль')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Фото')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
