# Generated by Django 5.2.1 on 2025-05-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to='employees/'),
        ),
    ]
