# Generated by Django 5.2.1 on 2025-05-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0009_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
