# Generated by Django 5.2.1 on 2025-05-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0002_owner_first_name_owner_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='n', max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='f', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='placeholder.png', upload_to='employees/'),
        ),
    ]
